### ISSUE TITLE
No contents in modeling_bert.py?

### ISSUE THREAD

**Issue by HarrytheOrange** [paulchhuang/bstro#6]
(czm) lsd@actev:~/czm/bstro-main$ python ./metro/tools/demo_bstro.py --num_hidden_layers 4 --num_attention_heads 4 --input_feat_dim 2051,512,128 --hidden_feat_dim 1024,256,128 --input_img samples/body-scene-contact/sample4.png--output_dir ./demo --resume_checkpoint models/bstro/hsi_hrnet_3dpw_b32_checkpoint_15.bin
Traceback (most recent call last):
  File "/home/lsd/czm/bstro-main/./metro/tools/demo_bstro.py", line 28, in <module>
    from metro.modeling.bert import BertConfig, METRO
  File "/home/lsd/czm/bstro-main/metro/modeling/bert/__init__.py", line 3, in <module>
    from .modeling_bert import (BertConfig, BertModel,
  File "/home/lsd/czm/bstro-main/metro/modeling/bert/modeling_bert.py", line 1
    ../../../transformers/pytorch_transformers/modeling_bert.py

**Comment by paulchhuang** [comment]
`modeling_bert.py` is in `transformers`, which we include as a submodule (not our code).
